### ISSUE TITLE
externs config

### ISSUE THREAD

**Issue by awb99** [bhauman/figwheel-main#141]
This questions might be stupid: I know that figwheel's main focus is on notifying changes during development to the browser. However, the fighwheel-main starter template includes also "min"
config, so I guess that figwheel main is also intende to be used as a "lein cljsbuild" replacement.

If so, then It would make sense to include a :externs flag into the configuration. The docs do not talk at all about how to set :externs flag in figwheel. I am not sure if it is possible to use it, or not.

Thanks.

**Comment by gmp26** [comment]
Me too! :)

I've also just come to the docs looking how to configure 'lein fig:min' to do externs.

**Comment by hiddenwaffle** [comment]
I was searching for this too and I believe it is implied by the section "Configuring a build" at https://figwheel.org/docs/create_a_build.html#configuring-a-build
that :externs would go into min.cljs.edn because that is where it talks about :main going. I have mine configured that way and it seems to be working.

**Comment by g1eny0ung** [comment]
@hiddenwaffle working for me. Thanks~
