### ISSUE TITLE
Watch local roots

### ISSUE THREAD

**Issue by olivergeorge** [bhauman/figwheel-main#164]
I think it'd be useful if figwheel watched the source paths of any :local/root deps.  Those paths are other places I'm likely to be editing code as part of debugging.

**Comment by bhauman** [comment]
It does sound like a nice feature, but you can add those directories to the `watch-dirs` and figwheel-main is trying to be independent of the build tool, because where does it stop? Figwheel doesn't currently look at the deps.edn file, but remember its not just the deps.edn file that determines the data its the aliaises on the command line, which aren't available to figwheel-main, and then there is the merging of the `~/.clojure/deps.edn`. 

So this really isn't possible at the moment.

**Comment by SevereOverfl0w** [comment]
kick is able to implement this feature by including all directories from the classpath. This does mean that :git/url dependencies are included also.

tools.deps does set various system properties when it starts the server, so you could use this to filter to only :local/root also.

I agree that this should be done via the API though.
